inhibit_all_warnings!
platform :ios, '8.0'
use_frameworks!

target 'Category' do
pod 'AFNetworking'
pod 'YYCache'
pod 'SDAutoLayout'
pod 'MJExtension'
pod 'MJRefresh'
pod 'pop'
pod 'SDCycleScrollView'
pod 'Masonry'
pod 'DACircularProgress'
pod 'SDWebImage', '~> 3.8.2'
pod 'YYText'
pod 'NSDate-Escort'
pod 'JHChainableAnimations'
pod 'MBProgressHUD'

# U-Share SDK UI模块（分享面板，建议添加）
pod ‘UMengUShare/UI’

# 集成微信(完整版14.4M)
pod ‘UMengUShare/Social/WeChat'

# 集成QQ/QZone/TIM(完整版7.6M)
pod ‘UMengUShare/Social/QQ'

# 集成新浪微博(完整版25.3M)
pod ‘UMengUShare/Social/Sina'

# 集成支付宝
pod ‘UMengUShare/Social/AlipayShare'

# 集成腾讯微博
pod ‘UMengUShare/Social/TencentWeibo'

# 集成邮件
pod ‘UMengUShare/Social/Email'

# 集成短信
pod ‘UMengUShare/Social/SMS'

# 加入IDFA获取
pod ‘UMengUShare/Plugin/IDFA'
end
