inhibit_all_warnings!
platform :ios, '8.0'
use_frameworks!

target 'Category' do
pod 'AFNetworking'
pod 'YYCache'
pod 'SDAutoLayout'
pod 'SDWebImage'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'YYWebImage'
pod 'pop'
pod 'SDCycleScrollView'
pod 'Masonry'
end
