inhibit_all_warnings!
platform :ios, '8.0'
use_frameworks!

target 'Category' do
pod 'AFNetworking'
pod 'YYCache'
pod 'SDAutoLayout'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'pop'
pod 'SDCycleScrollView'
pod 'Masonry'
pod 'DACircularProgress'
pod 'SDWebImage', '~> 3.8.2'
pod 'YYText'
pod 'Toast'
pod 'NSDate-Escort'
pod 'JHChainableAnimations'
end
